import './globals.css'
import Header from '@/components/Header/Header'

import { Kumbh_Sans } from 'next/font/google'

const kumbh = Kumbh_Sans({
    subsets: ['latin'],
    variable: '--font-kumbh',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={kumbh.variable}>
            <body>
                <div className="flex flex-col items-center">
                    <Header />
                    <main className="max-w-[1110px] w-full">{children}</main>
                </div>
            </body>
        </html>
    )
}
